export const fakeMatchesData2 = {
	filters: {
		season: '2025',
		matchday: '1',
	},
	resultSet: {
		count: 10,
		first: '2025-08-15',
		last: '2025-08-18',
		played: 10,
	},
	competition: {
		id: 2021,
		name: 'Premier League',
		code: 'PL',
		type: 'LEAGUE',
		emblem: 'https://crests.football-data.org/PL.png',
	},
	matches: [
		{
			area: {
				id: 2072,
				name: 'England',
				code: 'ENG',
				flag: 'https://crests.football-data.org/770.svg',
			},
			competition: {
				id: 2021,
				name: 'Premier League',
				code: 'PL',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/PL.png',
			},
			season: {
				id: 2403,
				startDate: '2025-08-15',
				endDate: '2026-05-24',
				currentMatchday: 3,
				winner: null,
			},
			id: 537785,
			utcDate: '2025-08-15T19:00:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:54Z',
			homeTeam: {
				id: 64,
				name: 'Liverpool FC',
				shortName: 'Liverpool',
				tla: 'LIV',
				crest: 'https://crests.football-data.org/64.png',
			},
			awayTeam: {
				id: 1044,
				name: 'AFC Bournemouth',
				shortName: 'Bournemouth',
				tla: 'BOU',
				crest: 'https://crests.football-data.org/bournemouth.png',
			},
			score: {
				winner: 'HOME_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 4,
					away: 2,
				},
				halfTime: {
					home: 1,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 11580,
					name: 'Anthony Taylor',
					type: 'REFEREE',
					nationality: 'England',
				},
			],
		},
		{
			area: {
				id: 2072,
				name: 'England',
				code: 'ENG',
				flag: 'https://crests.football-data.org/770.svg',
			},
			competition: {
				id: 2021,
				name: 'Premier League',
				code: 'PL',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/PL.png',
			},
			season: {
				id: 2403,
				startDate: '2025-08-15',
				endDate: '2026-05-24',
				currentMatchday: 3,
				winner: null,
			},
			id: 537786,
			utcDate: '2025-08-16T11:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:54Z',
			homeTeam: {
				id: 58,
				name: 'Aston Villa FC',
				shortName: 'Aston Villa',
				tla: 'AVL',
				crest: 'https://crests.football-data.org/58.png',
			},
			awayTeam: {
				id: 67,
				name: 'Newcastle United FC',
				shortName: 'Newcastle',
				tla: 'NEW',
				crest: 'https://crests.football-data.org/67.png',
			},
			score: {
				winner: 'DRAW',
				duration: 'REGULAR',
				fullTime: {
					home: 0,
					away: 0,
				},
				halfTime: {
					home: 0,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 11585,
					name: 'Craig Pawson',
					type: 'REFEREE',
					nationality: 'England',
				},
			],
		},
		{
			area: {
				id: 2072,
				name: 'England',
				code: 'ENG',
				flag: 'https://crests.football-data.org/770.svg',
			},
			competition: {
				id: 2021,
				name: 'Premier League',
				code: 'PL',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/PL.png',
			},
			season: {
				id: 2403,
				startDate: '2025-08-15',
				endDate: '2026-05-24',
				currentMatchday: 3,
				winner: null,
			},
			id: 537787,
			utcDate: '2025-08-16T14:00:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:54Z',
			homeTeam: {
				id: 397,
				name: 'Brighton & Hove Albion FC',
				shortName: 'Brighton Hove',
				tla: 'BHA',
				crest: 'https://crests.football-data.org/397.png',
			},
			awayTeam: {
				id: 63,
				name: 'Fulham FC',
				shortName: 'Fulham',
				tla: 'FUL',
				crest: 'https://crests.football-data.org/63.png',
			},
			score: {
				winner: 'DRAW',
				duration: 'REGULAR',
				fullTime: {
					home: 1,
					away: 1,
				},
				halfTime: {
					home: 0,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 213813,
					name: 'Sam Barrott',
					type: 'REFEREE',
					nationality: 'England',
				},
			],
		},
		{
			area: {
				id: 2072,
				name: 'England',
				code: 'ENG',
				flag: 'https://crests.football-data.org/770.svg',
			},
			competition: {
				id: 2021,
				name: 'Premier League',
				code: 'PL',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/PL.png',
			},
			season: {
				id: 2403,
				startDate: '2025-08-15',
				endDate: '2026-05-24',
				currentMatchday: 3,
				winner: null,
			},
			id: 537789,
			utcDate: '2025-08-16T14:00:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:54Z',
			homeTeam: {
				id: 71,
				name: 'Sunderland AFC',
				shortName: 'Sunderland',
				tla: 'SUN',
				crest: 'https://crests.football-data.org/71.png',
			},
			awayTeam: {
				id: 563,
				name: 'West Ham United FC',
				shortName: 'West Ham',
				tla: 'WHU',
				crest: 'https://crests.football-data.org/563.png',
			},
			score: {
				winner: 'HOME_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 3,
					away: 0,
				},
				halfTime: {
					home: 0,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 11446,
					name: 'Robert Jones',
					type: 'REFEREE',
					nationality: 'England',
				},
			],
		},
		{
			area: {
				id: 2072,
				name: 'England',
				code: 'ENG',
				flag: 'https://crests.football-data.org/770.svg',
			},
			competition: {
				id: 2021,
				name: 'Premier League',
				code: 'PL',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/PL.png',
			},
			season: {
				id: 2403,
				startDate: '2025-08-15',
				endDate: '2026-05-24',
				currentMatchday: 3,
				winner: null,
			},
			id: 537790,
			utcDate: '2025-08-16T14:00:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:54Z',
			homeTeam: {
				id: 73,
				name: 'Tottenham Hotspur FC',
				shortName: 'Tottenham',
				tla: 'TOT',
				crest: 'https://crests.football-data.org/73.png',
			},
			awayTeam: {
				id: 328,
				name: 'Burnley FC',
				shortName: 'Burnley',
				tla: 'BUR',
				crest: 'https://crests.football-data.org/328.png',
			},
			score: {
				winner: 'HOME_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 3,
					away: 0,
				},
				halfTime: {
					home: 1,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 11605,
					name: 'Michael Oliver',
					type: 'REFEREE',
					nationality: 'England',
				},
			],
		},
		{
			area: {
				id: 2072,
				name: 'England',
				code: 'ENG',
				flag: 'https://crests.football-data.org/770.svg',
			},
			competition: {
				id: 2021,
				name: 'Premier League',
				code: 'PL',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/PL.png',
			},
			season: {
				id: 2403,
				startDate: '2025-08-15',
				endDate: '2026-05-24',
				currentMatchday: 3,
				winner: null,
			},
			id: 537791,
			utcDate: '2025-08-16T16:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:54Z',
			homeTeam: {
				id: 76,
				name: 'Wolverhampton Wanderers FC',
				shortName: 'Wolverhampton',
				tla: 'WOL',
				crest: 'https://crests.football-data.org/76.png',
			},
			awayTeam: {
				id: 65,
				name: 'Manchester City FC',
				shortName: 'Man City',
				tla: 'MCI',
				crest: 'https://crests.football-data.org/65.png',
			},
			score: {
				winner: 'AWAY_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 0,
					away: 4,
				},
				halfTime: {
					home: 0,
					away: 2,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 23568,
					name: 'Jarred Gillett',
					type: 'REFEREE',
					nationality: 'Australia',
				},
			],
		},
		{
			area: {
				id: 2072,
				name: 'England',
				code: 'ENG',
				flag: 'https://crests.football-data.org/770.svg',
			},
			competition: {
				id: 2021,
				name: 'Premier League',
				code: 'PL',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/PL.png',
			},
			season: {
				id: 2403,
				startDate: '2025-08-15',
				endDate: '2026-05-24',
				currentMatchday: 3,
				winner: null,
			},
			id: 537788,
			utcDate: '2025-08-17T13:00:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:54Z',
			homeTeam: {
				id: 351,
				name: 'Nottingham Forest FC',
				shortName: 'Nottingham',
				tla: 'NOT',
				crest: 'https://crests.football-data.org/351.png',
			},
			awayTeam: {
				id: 402,
				name: 'Brentford FC',
				shortName: 'Brentford',
				tla: 'BRE',
				crest: 'https://crests.football-data.org/402.png',
			},
			score: {
				winner: 'HOME_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 3,
					away: 1,
				},
				halfTime: {
					home: 3,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 11309,
					name: 'Peter Bankes',
					type: 'REFEREE',
					nationality: 'England',
				},
			],
		},
		{
			area: {
				id: 2072,
				name: 'England',
				code: 'ENG',
				flag: 'https://crests.football-data.org/770.svg',
			},
			competition: {
				id: 2021,
				name: 'Premier League',
				code: 'PL',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/PL.png',
			},
			season: {
				id: 2403,
				startDate: '2025-08-15',
				endDate: '2026-05-24',
				currentMatchday: 3,
				winner: null,
			},
			id: 537792,
			utcDate: '2025-08-17T13:00:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:54Z',
			homeTeam: {
				id: 61,
				name: 'Chelsea FC',
				shortName: 'Chelsea',
				tla: 'CHE',
				crest: 'https://crests.football-data.org/61.png',
			},
			awayTeam: {
				id: 354,
				name: 'Crystal Palace FC',
				shortName: 'Crystal Palace',
				tla: 'CRY',
				crest: 'https://crests.football-data.org/354.png',
			},
			score: {
				winner: 'DRAW',
				duration: 'REGULAR',
				fullTime: {
					home: 0,
					away: 0,
				},
				halfTime: {
					home: 0,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 11469,
					name: 'Darren England',
					type: 'REFEREE',
					nationality: 'England',
				},
			],
		},
		{
			area: {
				id: 2072,
				name: 'England',
				code: 'ENG',
				flag: 'https://crests.football-data.org/770.svg',
			},
			competition: {
				id: 2021,
				name: 'Premier League',
				code: 'PL',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/PL.png',
			},
			season: {
				id: 2403,
				startDate: '2025-08-15',
				endDate: '2026-05-24',
				currentMatchday: 3,
				winner: null,
			},
			id: 537793,
			utcDate: '2025-08-17T15:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:54Z',
			homeTeam: {
				id: 66,
				name: 'Manchester United FC',
				shortName: 'Man United',
				tla: 'MUN',
				crest: 'https://crests.football-data.org/66.png',
			},
			awayTeam: {
				id: 57,
				name: 'Arsenal FC',
				shortName: 'Arsenal',
				tla: 'ARS',
				crest: 'https://crests.football-data.org/57.png',
			},
			score: {
				winner: 'AWAY_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 0,
					away: 1,
				},
				halfTime: {
					home: 0,
					away: 1,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 11430,
					name: 'Simon Hooper',
					type: 'REFEREE',
					nationality: 'England',
				},
			],
		},
		{
			area: {
				id: 2072,
				name: 'England',
				code: 'ENG',
				flag: 'https://crests.football-data.org/770.svg',
			},
			competition: {
				id: 2021,
				name: 'Premier League',
				code: 'PL',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/PL.png',
			},
			season: {
				id: 2403,
				startDate: '2025-08-15',
				endDate: '2026-05-24',
				currentMatchday: 3,
				winner: null,
			},
			id: 537794,
			utcDate: '2025-08-18T19:00:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:54Z',
			homeTeam: {
				id: 341,
				name: 'Leeds United FC',
				shortName: 'Leeds United',
				tla: 'LEE',
				crest: 'https://crests.football-data.org/341.png',
			},
			awayTeam: {
				id: 62,
				name: 'Everton FC',
				shortName: 'Everton',
				tla: 'EVE',
				crest: 'https://crests.football-data.org/62.png',
			},
			score: {
				winner: 'HOME_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 1,
					away: 0,
				},
				halfTime: {
					home: 0,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 11443,
					name: 'Chris Kavanagh',
					type: 'REFEREE',
					nationality: 'England',
				},
			],
		},
	],
};
