export const fakeMatchesData = {
	filters: {
		season: '2025',
		matchday: '1',
	},
	resultSet: {
		count: 9,
		first: '2025-08-22',
		last: '2025-08-24',
		played: 9,
	},
	competition: {
		id: 2002,
		name: 'Bundesliga',
		code: 'BL1',
		type: 'LEAGUE',
		emblem: 'https://crests.football-data.org/BL1.png',
	},
	matches: [
		{
			area: {
				id: 2088,
				name: 'Germany',
				code: 'DEU',
				flag: 'https://crests.football-data.org/759.svg',
			},
			competition: {
				id: 2002,
				name: 'Bundesliga',
				code: 'BL1',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/BL1.png',
			},
			season: {
				id: 2414,
				startDate: '2025-08-22',
				endDate: '2026-05-16',
				currentMatchday: 2,
				winner: null,
			},
			id: 540406,
			utcDate: '2025-08-22T18:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:53Z',
			homeTeam: {
				id: 5,
				name: 'FC Bayern München',
				shortName: 'Bayern',
				tla: 'FCB',
				crest: 'https://crests.football-data.org/5.png',
			},
			awayTeam: {
				id: 721,
				name: 'RB Leipzig',
				shortName: 'RB Leipzig',
				tla: 'RBL',
				crest: 'https://crests.football-data.org/721.png',
			},
			score: {
				winner: 'HOME_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 6,
					away: 0,
				},
				halfTime: {
					home: 3,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 57518,
					name: 'Florian Badstübner',
					type: 'REFEREE',
					nationality: 'Germany',
				},
			],
		},
		{
			area: {
				id: 2088,
				name: 'Germany',
				code: 'DEU',
				flag: 'https://crests.football-data.org/759.svg',
			},
			competition: {
				id: 2002,
				name: 'Bundesliga',
				code: 'BL1',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/BL1.png',
			},
			season: {
				id: 2414,
				startDate: '2025-08-22',
				endDate: '2026-05-16',
				currentMatchday: 2,
				winner: null,
			},
			id: 540407,
			utcDate: '2025-08-23T13:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:53Z',
			homeTeam: {
				id: 19,
				name: 'Eintracht Frankfurt',
				shortName: 'Frankfurt',
				tla: 'SGE',
				crest: 'https://crests.football-data.org/19.png',
			},
			awayTeam: {
				id: 12,
				name: 'SV Werder Bremen',
				shortName: 'Bremen',
				tla: 'SVW',
				crest: 'https://crests.football-data.org/12.png',
			},
			score: {
				winner: 'HOME_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 4,
					away: 1,
				},
				halfTime: {
					home: 2,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 253,
					name: 'Harm Osmers',
					type: 'REFEREE',
					nationality: 'Germany',
				},
			],
		},
		{
			area: {
				id: 2088,
				name: 'Germany',
				code: 'DEU',
				flag: 'https://crests.football-data.org/759.svg',
			},
			competition: {
				id: 2002,
				name: 'Bundesliga',
				code: 'BL1',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/BL1.png',
			},
			season: {
				id: 2414,
				startDate: '2025-08-22',
				endDate: '2026-05-16',
				currentMatchday: 2,
				winner: null,
			},
			id: 540408,
			utcDate: '2025-08-23T13:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:53Z',
			homeTeam: {
				id: 3,
				name: 'Bayer 04 Leverkusen',
				shortName: 'Leverkusen',
				tla: 'B04',
				crest: 'https://crests.football-data.org/3.png',
			},
			awayTeam: {
				id: 2,
				name: 'TSG 1899 Hoffenheim',
				shortName: 'Hoffenheim',
				tla: 'TSG',
				crest: 'https://crests.football-data.org/2.png',
			},
			score: {
				winner: 'AWAY_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 1,
					away: 2,
				},
				halfTime: {
					home: 1,
					away: 1,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 15408,
					name: 'Daniel Siebert',
					type: 'REFEREE',
					nationality: 'Germany',
				},
			],
		},
		{
			area: {
				id: 2088,
				name: 'Germany',
				code: 'DEU',
				flag: 'https://crests.football-data.org/759.svg',
			},
			competition: {
				id: 2002,
				name: 'Bundesliga',
				code: 'BL1',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/BL1.png',
			},
			season: {
				id: 2414,
				startDate: '2025-08-22',
				endDate: '2026-05-16',
				currentMatchday: 2,
				winner: null,
			},
			id: 540409,
			utcDate: '2025-08-23T13:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:53Z',
			homeTeam: {
				id: 17,
				name: 'SC Freiburg',
				shortName: 'Freiburg',
				tla: 'SCF',
				crest: 'https://crests.football-data.org/17.png',
			},
			awayTeam: {
				id: 16,
				name: 'FC Augsburg',
				shortName: 'Augsburg',
				tla: 'FCA',
				crest: 'https://crests.football-data.org/16.png',
			},
			score: {
				winner: 'AWAY_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 1,
					away: 3,
				},
				halfTime: {
					home: 0,
					away: 3,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 43878,
					name: 'Felix Zwayer',
					type: 'REFEREE',
					nationality: 'Germany',
				},
			],
		},
		{
			area: {
				id: 2088,
				name: 'Germany',
				code: 'DEU',
				flag: 'https://crests.football-data.org/759.svg',
			},
			competition: {
				id: 2002,
				name: 'Bundesliga',
				code: 'BL1',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/BL1.png',
			},
			season: {
				id: 2414,
				startDate: '2025-08-22',
				endDate: '2026-05-16',
				currentMatchday: 2,
				winner: null,
			},
			id: 540412,
			utcDate: '2025-08-23T13:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:53Z',
			homeTeam: {
				id: 28,
				name: '1. FC Union Berlin',
				shortName: 'Union Berlin',
				tla: 'UNB',
				crest: 'https://crests.football-data.org/28.png',
			},
			awayTeam: {
				id: 10,
				name: 'VfB Stuttgart',
				shortName: 'Stuttgart',
				tla: 'VFB',
				crest: 'https://crests.football-data.org/10.png',
			},
			score: {
				winner: 'HOME_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 2,
					away: 1,
				},
				halfTime: {
					home: 2,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 57504,
					name: 'Robert Hartmann',
					type: 'REFEREE',
					nationality: 'Germany',
				},
			],
		},
		{
			area: {
				id: 2088,
				name: 'Germany',
				code: 'DEU',
				flag: 'https://crests.football-data.org/759.svg',
			},
			competition: {
				id: 2002,
				name: 'Bundesliga',
				code: 'BL1',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/BL1.png',
			},
			season: {
				id: 2414,
				startDate: '2025-08-22',
				endDate: '2026-05-16',
				currentMatchday: 2,
				winner: null,
			},
			id: 540414,
			utcDate: '2025-08-23T13:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:53Z',
			homeTeam: {
				id: 44,
				name: '1. FC Heidenheim 1846',
				shortName: 'Heidenheim',
				tla: 'HEI',
				crest: 'https://crests.football-data.org/44.png',
			},
			awayTeam: {
				id: 11,
				name: 'VfL Wolfsburg',
				shortName: 'Wolfsburg',
				tla: 'WOB',
				crest: 'https://crests.football-data.org/11.png',
			},
			score: {
				winner: 'AWAY_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 1,
					away: 3,
				},
				halfTime: {
					home: 1,
					away: 1,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 43922,
					name: 'Benjamin Brand',
					type: 'REFEREE',
					nationality: 'Germany',
				},
			],
		},
		{
			area: {
				id: 2088,
				name: 'Germany',
				code: 'DEU',
				flag: 'https://crests.football-data.org/759.svg',
			},
			competition: {
				id: 2002,
				name: 'Bundesliga',
				code: 'BL1',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/BL1.png',
			},
			season: {
				id: 2414,
				startDate: '2025-08-22',
				endDate: '2026-05-16',
				currentMatchday: 2,
				winner: null,
			},
			id: 540413,
			utcDate: '2025-08-23T16:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:53Z',
			homeTeam: {
				id: 20,
				name: 'FC St. Pauli 1910',
				shortName: 'St. Pauli',
				tla: 'STP',
				crest: 'https://crests.football-data.org/20.png',
			},
			awayTeam: {
				id: 4,
				name: 'Borussia Dortmund',
				shortName: 'Dortmund',
				tla: 'BVB',
				crest: 'https://crests.football-data.org/4.png',
			},
			score: {
				winner: 'DRAW',
				duration: 'REGULAR',
				fullTime: {
					home: 3,
					away: 3,
				},
				halfTime: {
					home: 0,
					away: 1,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 56230,
					name: 'Matthias Jöllenbeck',
					type: 'REFEREE',
					nationality: 'Germany',
				},
			],
		},
		{
			area: {
				id: 2088,
				name: 'Germany',
				code: 'DEU',
				flag: 'https://crests.football-data.org/759.svg',
			},
			competition: {
				id: 2002,
				name: 'Bundesliga',
				code: 'BL1',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/BL1.png',
			},
			season: {
				id: 2414,
				startDate: '2025-08-22',
				endDate: '2026-05-16',
				currentMatchday: 2,
				winner: null,
			},
			id: 540410,
			utcDate: '2025-08-24T13:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:53Z',
			homeTeam: {
				id: 15,
				name: '1. FSV Mainz 05',
				shortName: 'Mainz',
				tla: 'M05',
				crest: 'https://crests.football-data.org/15.png',
			},
			awayTeam: {
				id: 1,
				name: '1. FC Köln',
				shortName: '1. FC Köln',
				tla: 'KOE',
				crest: 'https://crests.football-data.org/1.png',
			},
			score: {
				winner: 'AWAY_TEAM',
				duration: 'REGULAR',
				fullTime: {
					home: 0,
					away: 1,
				},
				halfTime: {
					home: 0,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 43943,
					name: 'Tobias Stieler',
					type: 'REFEREE',
					nationality: 'Germany',
				},
			],
		},
		{
			area: {
				id: 2088,
				name: 'Germany',
				code: 'DEU',
				flag: 'https://crests.football-data.org/759.svg',
			},
			competition: {
				id: 2002,
				name: 'Bundesliga',
				code: 'BL1',
				type: 'LEAGUE',
				emblem: 'https://crests.football-data.org/BL1.png',
			},
			season: {
				id: 2414,
				startDate: '2025-08-22',
				endDate: '2026-05-16',
				currentMatchday: 2,
				winner: null,
			},
			id: 540411,
			utcDate: '2025-08-24T15:30:00Z',
			status: 'FINISHED',
			matchday: 1,
			stage: 'REGULAR_SEASON',
			group: null,
			lastUpdated: '2025-08-31T00:20:53Z',
			homeTeam: {
				id: 18,
				name: 'Borussia Mönchengladbach',
				shortName: "M'gladbach",
				tla: 'BMG',
				crest: 'https://crests.football-data.org/18.png',
			},
			awayTeam: {
				id: 7,
				name: 'Hamburger SV',
				shortName: 'HSV',
				tla: 'HSV',
				crest: 'https://crests.football-data.org/7.png',
			},
			score: {
				winner: 'DRAW',
				duration: 'REGULAR',
				fullTime: {
					home: 0,
					away: 0,
				},
				halfTime: {
					home: 0,
					away: 0,
				},
			},
			odds: {
				msg: 'Activate Odds-Package in User-Panel to retrieve odds.',
			},
			referees: [
				{
					id: 9567,
					name: 'Sascha Stegemann',
					type: 'REFEREE',
					nationality: 'Germany',
				},
			],
		},
	],
};
