export const teamNameMap: Record<string, string> = {
	// EPL
	'Arsenal FC': 'Arsenal',
	'Aston Villa FC': 'AstonVilla',
	'AFC Bournemouth': 'Bournemouth',
	'Brentford FC': 'Brentford',
	'Brighton & Hove Albion FC': 'Brighton',
	'Burnley FC': 'Burnley',
	'Chelsea FC': 'Chelsea',
	'Crystal Palace FC': 'CrystalPalace',
	'Everton FC': 'Everton',
	'Fulham FC': 'Fulham',
	'Leeds United FC': 'Leeds',
	'Liverpool FC': 'Liverpool',
	'Manchester City FC': 'ManchesterCity',
	'Manchester United FC': 'ManchesterUnited',
	'Newcastle United FC': 'Newcastle',
	'Nottingham Forest FC': 'NottinghamForest',
	'Sunderland AFC': 'Sunderland',
	'Tottenham Hotspur FC': 'Tottenham',
	'West Ham United FC': 'WestHam',
	'Wolverhampton Wanderers FC': 'Wolverhampton',

	// Bundesliga
	'FC Augsburg': 'Augsburg',
	'Bayer 04 Leverkusen': 'BayerLeverkusen',
	'Borussia Dortmund': 'BorussiaDortmund',
	'Borussia Mönchengladbach': 'BorussiaMGladbach',
	'FC Bayern München': 'BayernMunich',
	'Eintracht Frankfurt': 'EintrachtFrankfurt',
	'SC Freiburg': 'Freiburg',
	'Hamburger SV': 'Hamburg',
	'1. FC Heidenheim 1846': 'Heidenheim',
	'TSG 1899 Hoffenheim': 'Hoffenheim',
	'1. FC Köln': 'Koln',
	'1. FSV Mainz 05': 'Mainz',
	'VfB Stuttgart': 'Stuttgart',
	'FC St. Pauli 1910': 'StPauli',
	'RB Leipzig': 'RBLeipzig',
	'1. FC Union Berlin': 'UnionBerlin',
	'VfL Wolfsburg': 'Wolfsburg',
	'SV Werder Bremen': 'WerderBremen',
};
